/*
 * This file is generated by jOOQ.
 */
package com.cbaeza.jooq.gradle.db.public_.tables.daos;


import com.cbaeza.jooq.gradle.db.public_.tables.Person;
import com.cbaeza.jooq.gradle.db.public_.tables.records.PersonRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonDao extends DAOImpl<PersonRecord, com.cbaeza.jooq.gradle.db.public_.tables.pojos.Person, Integer> {

    /**
     * Create a new PersonDao without any configuration
     */
    public PersonDao() {
        super(Person.PERSON, com.cbaeza.jooq.gradle.db.public_.tables.pojos.Person.class);
    }

    /**
     * Create a new PersonDao with an attached configuration
     */
    public PersonDao(Configuration configuration) {
        super(Person.PERSON, com.cbaeza.jooq.gradle.db.public_.tables.pojos.Person.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.cbaeza.jooq.gradle.db.public_.tables.pojos.Person object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.cbaeza.jooq.gradle.db.public_.tables.pojos.Person> fetchById(Integer... values) {
        return fetch(Person.PERSON.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.cbaeza.jooq.gradle.db.public_.tables.pojos.Person fetchOneById(Integer value) {
        return fetchOne(Person.PERSON.ID, value);
    }

    /**
     * Fetch records that have <code>NAME IN (values)</code>
     */
    public List<com.cbaeza.jooq.gradle.db.public_.tables.pojos.Person> fetchByName(String... values) {
        return fetch(Person.PERSON.NAME, values);
    }
}
