/*
 * This file is generated by jOOQ.
 */
package com.cbaeza.jooq.gradle.db.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Synonyms implements Serializable {

    private static final long serialVersionUID = -2035364382;

    private String  synonymCatalog;
    private String  synonymSchema;
    private String  synonymName;
    private String  synonymFor;
    private String  synonymForSchema;
    private String  typeName;
    private String  status;
    private String  remarks;
    private Integer id;

    public Synonyms() {}

    public Synonyms(Synonyms value) {
        this.synonymCatalog = value.synonymCatalog;
        this.synonymSchema = value.synonymSchema;
        this.synonymName = value.synonymName;
        this.synonymFor = value.synonymFor;
        this.synonymForSchema = value.synonymForSchema;
        this.typeName = value.typeName;
        this.status = value.status;
        this.remarks = value.remarks;
        this.id = value.id;
    }

    public Synonyms(
        String  synonymCatalog,
        String  synonymSchema,
        String  synonymName,
        String  synonymFor,
        String  synonymForSchema,
        String  typeName,
        String  status,
        String  remarks,
        Integer id
    ) {
        this.synonymCatalog = synonymCatalog;
        this.synonymSchema = synonymSchema;
        this.synonymName = synonymName;
        this.synonymFor = synonymFor;
        this.synonymForSchema = synonymForSchema;
        this.typeName = typeName;
        this.status = status;
        this.remarks = remarks;
        this.id = id;
    }

    public String getSynonymCatalog() {
        return this.synonymCatalog;
    }

    public void setSynonymCatalog(String synonymCatalog) {
        this.synonymCatalog = synonymCatalog;
    }

    public String getSynonymSchema() {
        return this.synonymSchema;
    }

    public void setSynonymSchema(String synonymSchema) {
        this.synonymSchema = synonymSchema;
    }

    public String getSynonymName() {
        return this.synonymName;
    }

    public void setSynonymName(String synonymName) {
        this.synonymName = synonymName;
    }

    public String getSynonymFor() {
        return this.synonymFor;
    }

    public void setSynonymFor(String synonymFor) {
        this.synonymFor = synonymFor;
    }

    public String getSynonymForSchema() {
        return this.synonymForSchema;
    }

    public void setSynonymForSchema(String synonymForSchema) {
        this.synonymForSchema = synonymForSchema;
    }

    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Synonyms (");

        sb.append(synonymCatalog);
        sb.append(", ").append(synonymSchema);
        sb.append(", ").append(synonymName);
        sb.append(", ").append(synonymFor);
        sb.append(", ").append(synonymForSchema);
        sb.append(", ").append(typeName);
        sb.append(", ").append(status);
        sb.append(", ").append(remarks);
        sb.append(", ").append(id);

        sb.append(")");
        return sb.toString();
    }
}
